# Leer y Escribir

In [1]:
import pandas as pd
#Leer de un CSV
df_penguins = pd.read_csv('penguins.csv')
df_penguins.head(2)

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,1,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,2,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007

In [2]:
#Escribir DataFrame a CSV
df_penguins.to_csv('penguins.csv', index=False)#Convierte DataFrame a CSV sin incluir nombre de fila

# Mezclar y Mostrar

In [3]:
df_shuffled = df_penguins.sample(frac=1) #Selecciona el total de filas y las mezcla
df_shuffled.head(2)

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
16,17,Adelie,Torgersen,38.7,19.0,195.0,3450.0,female,2007
339,340,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009

In [4]:
df_sampled = df_penguins.sample(frac=0.5)
print(f"Longitud original: {len(df_penguins)}; Longitud sampled: {len(df_sampled)}")

Longitud original: 344; Longitud sampled: 172

# Añadiendo columnas

In [5]:
import pandas as pd
df = pd.DataFrame({'temp_celcius': [35.0, 25.0]}, index=['Delhi','Mumbai'])
df

        temp_celcius
Delhi           35.0
Mumbai          25.0

In [6]:
speed_values = [26.0, 31.0]
df = df.assign(wind_speed_kmph=speed_values)
df

        temp_celcius  wind_speed_kmph
Delhi           35.0             26.0
Mumbai          25.0             31.0

In [7]:
df = df.assign(wind_speed_mph = lambda x: x['wind_speed_kmph']*0.621)
df

        temp_celcius  wind_speed_kmph  wind_speed_mph
Delhi           35.0             26.0          16.146
Mumbai          25.0             31.0          19.251

In [8]:
df.assign(temp_fahrenheit=lambda x: x['temp_celcius'] * 9/5 +32,
          temp_kelvin= lambda x:(x['temp_fahrenheit']+ 459.67)*5/9)

,temp_celcius,wind_speed_kmph,wind_speed_mph,temp_fahrenheit,temp_kelvin
Delhi,35.0,26.0,16.146,95.0,308.15
Mumbai,25.0,31.0,19.251,77.0,298.15

---
# **.describe()**
---

Si la columna es numérica:
Te da estadísticas básicas como:
- count: número de valores no nulos
- mean: media
- std: desviación estándar
- min: mínimo
- 25%: percentil 25
- 50%: percentil 50 (la mediana)
- 75%: percentil 75
- max: máximo

Si la columna es de tipo objeto o categórica:
- count: número de valores no nulos
- unique: número de valores únicos
- top: valor más frecuente
- freq: frecuencia del valor más frecuente

In [9]:
import pandas as pd

stocks = pd.read_csv("stocks.csv")
stocks.head(2)

,Index,Date,Open,High,Low,Close,Adj Close,Volume,CloseUSD
0,HSI,1986-12-31,2568.300049,2568.300049,2568.300049,2568.300049,2568.300049,0.0,333.879006
1,HSI,1987-01-02,2540.100098,2540.100098,2540.100098,2540.100098,2540.100098,0.0,330.213013

In [10]:
stocks.describe()

,Open,High,Low,Close,Adj Close,Volume,CloseUSD
count,104224.000000,104224.000000,104224.000000,104224.000000,104224.000000,1.042240e+05,104224.000000
mean,8015.353334,8063.324234,7962.581120,8014.366642,8014.161269,1.347646e+09,3046.729177
std,9140.563404,9196.575802,9082.767802,9140.609758,9140.720456,4.427662e+09,3747.865623
min,54.869999,54.869999,54.869999,54.869999,54.869999,0.000000e+00,10.204900
25%,2046.887756,2057.213990,2037.185943,2047.506470,2047.358490,0.000000e+00,320.460898
50%,5772.140137,5812.764892,5725.199951,5773.710205,5773.710205,9.529000e+05,1371.598486
75%,10487.377445,10552.179690,10416.092287,10488.622560,10488.622560,2.064676e+08,4383.045241
max,68775.062500,69403.750000,68516.992190,68775.062500,68775.062500,9.440374e+10,18934.376173

In [11]:
perc = [.50, .90]
subsets = pd.IndexSlice[['90%'], 'Open']
stocks.describe(percentiles = perc).style.map(lambda x: "background-color: magenta", subset=subsets)
	# 1.	Calcula estadísticas de stocks con percentiles 50% y 90%.
	# 2.	Selecciona la celda del percentil 90 de la columna Open.
	# 3.	Pinta esa celda de magenta en la salida de Jupyter Notebook.

---
# **.apply()**
---
Sirve para aplicar una función a lo largo de un eje de un DataFrame o a cada elemento de una Series.

- axis=0 (por defecto): aplica la función columna por columna.
- axis=1: aplica la función fila por fila.

In [12]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'A': [1,2], 'B':[4,5]})
df

   A  B
0  1  4
1  2  5

In [13]:
df.apply(func = np.sum, axis = 0)

A    3
B    9
dtype: int64

In [14]:
df.apply(func = np.sum, axis=1)

0    5
1    7
dtype: int64

In [15]:
A_plus_B = df.apply(func = lambda row: row['A'] + row['B'], axis=1)
df['A_plus_B'] = A_plus_B
df

   A  B  A_plus_B
0  1  4         5
1  2  5         7

In [16]:
df.apply(func = lambda col: (col[0] + col[1])/2, axis=0)

A           1.5
B           4.5
A_plus_B    6.0
dtype: float64

---
# .groupby()
---

Sirve para agrupar filas de un DataFrame en función de una o varias columnas, y luego aplicar cálculos sobre cada grupo.

In [17]:
import pandas as pd

df = pd.read_csv('weather.csv')
df.head(2)

,Data.Precipitation,Date.Full,Date.Month,Date.Week of,Date.Year,Station.City,Station.Code,Station.Location,Station.State,Data.Temperature.Avg Temp,Data.Temperature.Max Temp,Data.Temperature.Min Temp,Data.Wind.Direction,Data.Wind.Speed
0,0.0,2016-01-03,1,3,2016,Birmingham,BHM,"Birmingham, AL",Alabama,39,46,32,33,4.33
1,0.0,2016-01-03,1,3,2016,Huntsville,HSV,"Huntsville, AL",Alabama,39,47,31,32,3.86

In [18]:
for city, city_df in df.groupby('Station.City'):
    print(city)
    print(city_df)

Aberdeen
       Data.Precipitation   Date.Full  Date.Month  Date.Week of  Date.Year  \
249                  0.00  2016-01-03           1             3       2016
564                  0.04  2016-01-10           1            10       2016
879                  0.05  2016-01-17           1            17       2016
1194                 0.03  2016-01-24           1            24       2016
1509                 0.02  2016-01-31           1            31       2016
1824                 0.04  2016-02-07           2             7       2016
2139                 0.42  2016-02-14           2            14       2016
2454                 0.05  2016-02-21           2            21       2016
2769                 0.01  2016-02-28           2            28       2016
3086                 0.03  2016-03-06           3             6       2016
3401                 0.09  2016-03-13           3            13       2016
3716                 0.12  2016-03-20           3            20       2016
4031                 0.00  2016-03-27           3            27       2016
4348                 0.00  2016-04-03           4             3       2016
4664                 0.09  2016-04-10           4            10       2016
4980                 1.32  2016-04-17           4            17       2016
5296                 1.20  2016-04-24           4            24       2016
5613                 0.00  2016-05-01           5             1       2016
5930                 0.00  2016-05-08           5             8       2016
6247                 0.69  2016-05-15           5            15       2016
6564                 0.15  2016-05-22           5            22       2016
6881                 0.83  2016-05-29           5            29       2016
7198                 0.78  2016-06-05           6             5       2016
7513                 0.00  2016-06-12           6            12       2016
7828                 0.62  2016-06-19           6            19       2016
8143                 0.01  2016-06-26           6            26       2016
8459                 0.00  2016-07-03           7             3       2016
8774                 0.83  2016-07-10           7            10       2016
9088                 1.87  2016-07-17           7            17       2016
9402                 0.12  2016-07-24           7            24       2016
9716                 0.87  2016-07-31           7            31       2016
10032                0.15  2016-08-07           8             7       2016
10349                1.38  2016-08-14           8            14       2016
10666                0.46  2016-08-21           8            21       2016
10983                0.01  2016-08-28           8            28       2016
11300                0.34  2016-09-04           9             4       2016
11616                0.07  2016-09-11           9            11       2016
11932                0.65  2016-09-18           9            18       2016
12248                0.17  2016-09-25           9            25       2016
12565                0.00  2016-10-02          10             2       2016
12882                0.65  2016-10-09          10             9       2016
13199                0.00  2016-10-16          10            16       2016
13516                0.02  2016-10-23          10            23       2016
13833                1.14  2016-10-30          10            30       2016
14150                0.00  2016-11-06          11             6       2016
14464                0.00  2016-11-13          11            13       2016
14778                0.23  2016-11-20          11            20       2016
15092                0.74  2016-11-27          11            27       2016
15409                0.00  2016-12-04          12             4       2016
15726                0.20  2016-12-11          12            11       2016
16043                0.29  2016-12-18          12            18       2016
16360                1.28  2016-12-25          12            25       2016
16677                0.01  2017-01-01           1             1       2017

      Station.City Station.Code Station.Location Station.State  \
249       Aberdeen          ABR     Aberdeen, SD  South Dakota
564       Aberdeen          ABR     Aberdeen, SD  South Dakota
879       Aberdeen          ABR     Aberdeen, SD  South Dakota
1194      Aberdeen          ABR     Aberdeen, SD  South Dakota
1509      Aberdeen          ABR     Aberdeen, SD  South Dakota
1824      Aberdeen          ABR     Aberdeen, SD  South Dakota
2139      Aberdeen          ABR     Aberdeen, SD  South Dakota
2454      Aberdeen          ABR     Aberdeen, SD  South Dakota
2769      Aberdeen          ABR     Aberdeen, SD  South Dakota
3086      Aberdeen          ABR     Aberdeen, SD  South Dakota
3401      Aberdeen          ABR     Aberdeen, SD  South Dakota
3716      Aberdeen          ABR     Aberdeen, SD  South Dakota
4031      Aberdeen          ABR     Aberdeen, SD  South Dakota
4348      Aberdeen          ABR     Aberdeen, SD  South Dakota
4664      Aberdeen          ABR     Aberdeen, SD  South Dakota
4980      Aberdeen          ABR     Aberdeen, SD  South Dakota
5296      Aberdeen          ABR     Aberdeen, SD  South Dakota
5613      Aberdeen          ABR     Aberdeen, SD  South Dakota
5930      Aberdeen          ABR     Aberdeen, SD  South Dakota
6247      Aberdeen          ABR     Aberdeen, SD  South Dakota
6564      Aberdeen          ABR     Aberdeen, SD  South Dakota
6881      Aberdeen          ABR     Aberdeen, SD  South Dakota
7198      Aberdeen          ABR     Aberdeen, SD  South Dakota
7513      Aberdeen          ABR     Aberdeen, SD  South Dakota
7828      Aberdeen          ABR     Aberdeen, SD  South Dakota
8143      Aberdeen          ABR     Aberdeen, SD  South Dakota
8459      Aberdeen          ABR     Aberdeen, SD  South Dakota
8774      Aberdeen          ABR     Aberdeen, SD  South Dakota
9088      Aberdeen          ABR     Aberdeen, SD  South Dakota
9402      Aberdeen          ABR     Aberdeen, SD  South Dakota
9716      Aberdeen          ABR     Aberdeen, SD  South Dakota
10032     Aberdeen          ABR     Aberdeen, SD  South Dakota
10349     Aberdeen          ABR     Aberdeen, SD  South Dakota
10666     Aberdeen          ABR     Aberdeen, SD  South Dakota
10983     Aberdeen          ABR     Aberdeen, SD  South Dakota
11300     Aberdeen          ABR     Aberdeen, SD  South Dakota
11616     Aberdeen          ABR     Aberdeen, SD  South Dakota
11932     Aberdeen          ABR     Aberdeen, SD  South Dakota
12248     Aberdeen          ABR     Aberdeen, SD  South Dakota
12565     Aberdeen          ABR     Aberdeen, SD  South Dakota
12882     Aberdeen          ABR     Aberdeen, SD  South Dakota
13199     Aberdeen          ABR     Aberdeen, SD  South Dakota
13516     Aberdeen          ABR     Aberdeen, SD  South Dakota
13833     Aberdeen          ABR     Aberdeen, SD  South Dakota
14150     Aberdeen          ABR     Aberdeen, SD  South Dakota
14464     Aberdeen          ABR     Aberdeen, SD  South Dakota
14778     Aberdeen          ABR     Aberdeen, SD  South Dakota
15092     Aberdeen          ABR     Aberdeen, SD  South Dakota
15409     Aberdeen          ABR     Aberdeen, SD  South Dakota
15726     Aberdeen          ABR     Aberdeen, SD  South Dakota
16043     Aberdeen          ABR     Aberdeen, SD  South Dakota
16360     Aberdeen          ABR     Aberdeen, SD  South Dakota
16677     Aberdeen          ABR     Aberdeen, SD  South Dakota

       Data.Temperature.Avg Temp  Data.Temperature.Max Temp  \
249                           18                         29
564                           15                         23
879                            7                         17
1194                          17                         23
1509                          31                         40
1824                          28                         37
2139                          16                         24
2454                          33                         39
2769                          35                         46
3086                          34                         45
3401                          47                         62
3716                          39                         49
4031                          37                         51
4348                          41                         56
4664                          38                         52
4980                          49                         62
5296                          53                         66
5613                          48                         64
5930                          59                         78
6247                          51                         63
6564                          60                         75
6881                          66                         78
7198                          62                         76
7513                          74                         88
7828                          74                         86
8143                          71                         86
8459                          65                         81
8774                          72                         85
9088                          67                         80
9402                          78                         90
9716                          73                         84
10032                         72                         85
10349                         73                         86
10666                         69                         81
10983                         68                         81
11300                         73                         84
11616                         63                         75
11932                         60                         72
12248                         63                         74
12565                         65                         78
12882                         49                         61
13199                         51                         65
13516                         46                         59
13833                         49                         57
14150                         52                         68
14464                         46                         62
14778                         35                         44
15092                         32                         40
15409                         29                         35
15726                          8                         16
16043                         -6                          7
16360                         22                         32
16677                         21                         31

       Data.Temperature.Min Temp  Data.Wind.Direction  Data.Wind.Speed
249                            7                   26             6.16
564                            6                   18             9.91
879                           -3                   24             7.18
1194                          10                   11             8.00
1509                          22                   27             7.50
1824                          19                   23             8.81
2139                           9                   12            10.48
2454                          26                   17             8.62
2769                          24                   27             8.22
3086                          23                   17             6.91
3401                          32                   16             7.77
3716                          29                   28            10.75
4031                          22                    8             9.82
4348                          26                   33             7.53
4664                          24                   25            12.88
4980                          34                   17            11.00
5296                          40                   13            10.37
5613                          31                   36             6.80
5930                          39                   22             6.61
6247                          38                   24            10.61
6564                          45                   12            13.15
6881                          53                   15             4.52
7198                          48                   26            10.98
7513                          60                   12             7.54
7828                          61                   19             7.17
8143                          56                   22             9.45
8459                          48                   16             7.06
8774                          58                   17             6.77
9088                          54                   21             7.98
9402                          65                   12             6.05
9716                          61                   11             7.27
10032                         59                   13             7.34
10349                         60                   17             7.61
10666                         56                   21             6.07
10983                         55                   20            10.00
11300                         61                   16            15.85
11616                         51                   20             5.92
11932                         46                   24             7.25
12248                         52                   14            12.10
12565                         50                   15            12.15
12882                         36                   19            11.38
13199                         37                   22             9.24
13516                         32                   25             6.01
13833                         40                   18             6.81
14150                         35                   21             6.28
14464                         30                   23             6.94
14778                         25                   20             9.21
15092                         24                   17             4.82
15409                         23                   27             8.17
15726                          0                   27            13.27
16043                        -20                   21             9.67
16360                         11                   18            11.91
16677                         12                   26            12.05
Abilene
       Data.Precipitation   Date.Full  Date.Month  Date.Week of  Date.Year  \
262                  0.00  2016-01-03           1             3       2016
577                  0.04  2016-01-10           1            10       2016
892                  0.00  2016-01-17           1            17       2016
1207                 0.00  2016-01-24           1            24       2016
1522                 0.00  2016-01-31           1            31       2016
1837                 0.00  2016-02-07           2             7       2016
2152                 0.00  2016-02-14           2            14       2016
2467                 0.00  2016-02-21           2            21       2016
2782                 0.68  2016-02-28           2            28       2016
3099                 0.00  2016-03-06           3             6       2016
3414                 2.31  2016-03-13           3            13       2016
3729                 0.00  2016-03-20           3            20       2016
4044                 0.00  2016-03-27           3            27       2016
4361                 0.00  2016-04-03           4             3       2016
4677                 0.66  2016-04-10           4            10       2016
4993                 3.54  2016-04-17           4            17       2016
5309                 1.46  2016-04-24           4            24       2016
5626                 0.00  2016-05-01           5             1       2016
5943                 1.65  2016-05-08           5             8       2016
6260                 3.27  2016-05-15           5            15       2016
6577                 0.55  2016-05-22           5            22       2016
6894                 2.77  2016-05-29           5            29       2016
7211                 2.32  2016-06-05           6             5       2016
7526                 0.17  2016-06-12           6            12       2016
7841                 0.00  2016-06-19           6            19       2016
8156                 0.00  2016-06-26           6            26       2016
8472                 0.00  2016-07-03           7             3       2016
8786                 0.40  2016-07-10           7            10       2016
9100                 0.00  2016-07-17           7            17       2016
9414                 0.00  2016-07-24           7            24       2016
9728                 0.24  2016-07-31           7            31       2016
10045                0.00  2016-08-07           8             7       2016
10362                0.65  2016-08-14           8            14       2016
10679                2.65  2016-08-21           8            21       2016
10996                1.97  2016-08-28           8            28       2016
11313                1.20  2016-09-04           9             4       2016
11629                0.29  2016-09-11           9            11       2016
11945                1.45  2016-09-18           9            18       2016
12261                2.64  2016-09-25           9            25       2016
12578                0.00  2016-10-02          10             2       2016
12895                0.08  2016-10-09          10             9       2016
13212                0.32  2016-10-16          10            16       2016
13529                0.00  2016-10-23          10            23       2016
13846                0.00  2016-10-30          10            30       2016
14163                1.97  2016-11-06          11             6       2016
14477                0.50  2016-11-13          11            13       2016
14791                0.00  2016-11-20          11            20       2016
15105                0.04  2016-11-27          11            27       2016
15422                1.19  2016-12-04          12             4       2016
15739                0.20  2016-12-11          12            11       2016
16056                0.00  2016-12-18          12            18       2016
16373                0.00  2016-12-25          12            25       2016
16690                0.00  2017-01-01           1             1       2017

      Station.City Station.Code Station.Location Station.State  \
262        Abilene          ABI      Abilene, TX         Texas
577        Abilene          ABI      Abilene, TX         Texas
892        Abilene          ABI      Abilene, TX         Texas
1207       Abilene          ABI      Abilene, TX         Texas
1522       Abilene          ABI      Abilene, TX         Texas
1837       Abilene          ABI      Abilene, TX         Texas
2152       Abilene          ABI      Abilene, TX         Texas
2467       Abilene          ABI      Abilene, TX         Texas
2782       Abilene          ABI      Abilene, TX         Texas
3099       Abilene          ABI      Abilene, TX         Texas
3414       Abilene          ABI      Abilene, TX         Texas
3729       Abilene          ABI      Abilene, TX         Texas
4044       Abilene          ABI      Abilene, TX         Texas
4361       Abilene          ABI      Abilene, TX         Texas
4677       Abilene          ABI      Abilene, TX         Texas
4993       Abilene          ABI      Abilene, TX         Texas
5309       Abilene          ABI      Abilene, TX         Texas
5626       Abilene          ABI      Abilene, TX         Texas
5943       Abilene          ABI      Abilene, TX         Texas
6260       Abilene          ABI      Abilene, TX         Texas
6577       Abilene          ABI      Abilene, TX         Texas

In [19]:
df.groupby('Station.City').max()

,Data.Precipitation,Date.Full,Date.Month,Date.Week of,Date.Year,Station.Code,Station.Location,Station.State,Data.Temperature.Avg Temp,Data.Temperature.Max Temp,Data.Temperature.Min Temp,Data.Wind.Direction,Data.Wind.Speed
Station.City,,,,,,,,,,,,,
Aberdeen,1.87,2017-01-01,12,31,2017,ABR,"Aberdeen, SD",South Dakota,78,90,65,36,15.85
Abilene,3.54,2017-01-01,12,31,2017,ABI,"Abilene, TX",Texas,89,100,77,26,14.60
Akron,3.04,2017-01-01,12,31,2017,CAK,"Akron, OH",Ohio,79,89,70,31,12.11
Alamosa,1.82,2017-01-01,12,31,2017,ALS,"Alamosa, CO",Colorado,69,87,51,32,7.80
Albany,3.25,2017-01-01,12,31,2017,ALB,"Albany, NY",New York,78,88,68,32,11.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Worcester,4.29,2017-01-01,12,31,2017,ORH,"Worcester, MA",Massachusetts,76,85,66,29,14.91
Wrangell,0.00,2017-01-01,12,30,2017,WRG,"Wrangell, AK",Alaska,60,60,60,29,10.87
Yakima,0.98,2017-01-01,12,31,2017,YKM,"Yakima, WA",Washington,83,99,67,33,7.56
Yakutat,6.96,2017-01-01,12,31,2017,YAK,"Yakutat, AK",Alaska,60,66,55,27,8.20
Youngstown/Warren,5.05,2017-01-01,12,31,2017,YNG,"Youngstown/Warren, OH",Ohio,77,87,67,30,11.23

In [20]:
df.groupby('Station.City').describe()

                  Data.Precipitation                                       \
                               count      mean       std  min   25%   50%
Station.City
Aberdeen                        53.0  0.340943  0.463529  0.0  0.01  0.09
Abilene                         53.0  0.664340  1.001410  0.0  0.00  0.04
Akron                           53.0  0.628679  0.634647  0.0  0.10  0.54
Alamosa                         53.0  0.154151  0.307636  0.0  0.00  0.02
Albany                          53.0  0.583019  0.716344  0.0  0.07  0.27
...                              ...       ...       ...  ...   ...   ...
Worcester                       53.0  0.691887  0.764365  0.0  0.18  0.47
Wrangell                        30.0  0.000000  0.000000  0.0  0.00  0.00
Yakima                          53.0  0.187925  0.278135  0.0  0.00  0.06
Yakutat                         53.0  2.073585  1.874223  0.0  0.47  1.64
Youngstown/Warren               53.0  0.727925  0.843528  0.0  0.15  0.56

                              Date.Month            ... Data.Wind.Direction  \
                    75%   max      count      mean  ...                 75%
Station.City                                        ...
Aberdeen           0.65  1.87       53.0  6.339623  ...                24.0
Abilene            1.19  3.54       53.0  6.339623  ...                20.0
Akron              0.76  3.04       53.0  6.339623  ...                24.0
Alamosa            0.17  1.82       53.0  6.339623  ...                24.0
Albany             0.90  3.25       53.0  6.339623  ...                25.0
...                 ...   ...        ...       ...  ...                 ...
Worcester          1.12  4.29       53.0  6.339623  ...                26.0
Wrangell           0.00  0.00       30.0  7.000000  ...                21.0
Yakima             0.26  0.98       53.0  6.339623  ...                28.0
Yakutat            3.04  6.96       53.0  6.339623  ...                16.0
Youngstown/Warren  1.04  5.05       53.0  6.339623  ...                23.0

                        Data.Wind.Speed                                    \
                    max           count      mean       std   min     25%
Station.City
Aberdeen           36.0            53.0  8.753208  2.435565  4.52  6.9400
Abilene            26.0            53.0  8.646604  2.111289  4.92  7.0700
Akron              31.0            53.0  7.391132  2.452797  2.50  5.6200
Alamosa            32.0            53.0  3.789434  1.689355  0.80  2.2800
Albany             32.0            53.0  6.161509  1.818222  2.42  5.2000
...                 ...             ...       ...       ...   ...     ...
Worcester          29.0            53.0  8.485660  2.057286  5.00  7.0000
Wrangell           29.0            30.0  4.269333  2.473163  1.35  2.2125
Yakima             33.0            53.0  3.747925  1.294927  1.44  2.8200
Yakutat            27.0            53.0  3.631509  1.897979  0.00  2.4200
Youngstown/Warren  30.0            53.0  6.656604  2.279640  1.40  4.8700


                    50%    75%    max
Station.City
Aberdeen           8.00  10.48  15.85
Abilene            8.65   9.81  14.60
Akron              7.15   9.17  12.11
Alamosa            4.11   5.20   7.80
Albany             6.05   7.22  11.60
...                 ...    ...    ...
Worcester          8.02   9.97  14.91
Wrangell           3.91   5.42  10.87
Yakima             3.41   4.45   7.56
Yakutat            3.35   4.82   8.20
Youngstown/Warren  6.60   8.44  11.23

[307 rows x 72 columns]

---
# .iterrows() | .itertuples()
---

- .iterrows(): 
    - Devuelve cada fila como una tupla (índice, fila)
    - Donde fila es una pandas Series
- .itertuples():
    - Devuelve cada fila como un namedtuple (objeto tipo tupla con nombres de campo)
    - Es más rápido y eficiente que iterrows()

In [21]:
import pandas as pd
df_penguins = pd.read_csv('penguins.csv')

In [22]:
%%time
index_series_pairs = [pair for pair in df_penguins.iterrows()]
idx, series = index_series_pairs[0]
print('idx', idx)
print('__________________________')
print(series)
print('________time taken________')

idx 0
__________________________
rowid                        1
species                 Adelie
island               Torgersen
bill_length_mm            39.1
bill_depth_mm             18.7
flipper_length_mm        181.0
body_mass_g             3750.0
sex                       male
year                      2007
Name: 0, dtype: object
________time taken________
CPU times: user 26.6 ms, sys: 3.77 ms, total: 30.4 ms
Wall time: 27.7 ms

In [23]:
%%time
named_tuples = [tup for tup in df_penguins.itertuples()]
print(named_tuples[0])
print('________time taken________')

Pandas(Index=0, rowid=1, species='Adelie', island='Torgersen', bill_length_mm=39.1, bill_depth_mm=18.7, flipper_length_mm=181.0, body_mass_g=3750.0, sex='male', year=2007)
________time taken________
CPU times: user 1.64 ms, sys: 0 ns, total: 1.64 ms
Wall time: 1.67 ms

---
# .loc[]
---
Se usa para acceder a filas y columnas por sus etiquetas (nombres), no por posición numérica.

In [24]:
import pandas as pd
df = pd.read_csv('penguins.csv')
df.head(4)

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,1,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,2,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,3,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,4,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007

In [25]:
#Usando un índice
df.loc[2]

rowid                        3
species                 Adelie
island               Torgersen
bill_length_mm            40.3
bill_depth_mm             18.0
flipper_length_mm        195.0
body_mass_g             3250.0
sex                     female
year                      2007
Name: 2, dtype: object

In [26]:
#slice
df.loc[0:3:2]

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,1,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
2,3,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007

In [27]:
df.loc[1:2, ['species', 'sex']]

  species     sex
1  Adelie  female
2  Adelie  female

In [28]:
df.loc[(df['bill_length_mm'] > 50.5) & (df['sex'] == 'female')]

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
293,294,Chinstrap,Dream,58.0,17.8,181.0,3700.0,female,2007
320,321,Chinstrap,Dream,50.9,17.9,196.0,3675.0,female,2009

---
# .sort_values()
---

Sirve para ordenar las filas de un DataFrame o los elementos de una Serie según una o varias columnas

In [29]:
import pandas as pd
df = pd.read_csv('penguins.csv').sample(frac=0.012)
df.head()

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
283,284,Chinstrap,Dream,51.3,18.2,197.0,3750.0,male,2007
181,182,Gentoo,Biscoe,50.0,15.3,220.0,5550.0,male,2007
312,313,Chinstrap,Dream,47.6,18.3,195.0,3850.0,female,2008
15,16,Adelie,Torgersen,36.6,17.8,185.0,3700.0,female,2007

In [30]:
df.sort_values(by=['species'])

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
15,16,Adelie,Torgersen,36.6,17.8,185.0,3700.0,female,2007
283,284,Chinstrap,Dream,51.3,18.2,197.0,3750.0,male,2007
312,313,Chinstrap,Dream,47.6,18.3,195.0,3850.0,female,2008
181,182,Gentoo,Biscoe,50.0,15.3,220.0,5550.0,male,2007

In [31]:
df.sort_values(by=['species', 'bill_length_mm'])

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
15,16,Adelie,Torgersen,36.6,17.8,185.0,3700.0,female,2007
312,313,Chinstrap,Dream,47.6,18.3,195.0,3850.0,female,2008
283,284,Chinstrap,Dream,51.3,18.2,197.0,3750.0,male,2007
181,182,Gentoo,Biscoe,50.0,15.3,220.0,5550.0,male,2007

In [32]:
df.sort_values(
    by=['bill_length_mm', 'bill_depth_mm'],
    key=lambda x: df['bill_depth_mm'] + df['bill_length_mm']
)

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
15,16,Adelie,Torgersen,36.6,17.8,185.0,3700.0,female,2007
181,182,Gentoo,Biscoe,50.0,15.3,220.0,5550.0,male,2007
312,313,Chinstrap,Dream,47.6,18.3,195.0,3850.0,female,2008
283,284,Chinstrap,Dream,51.3,18.2,197.0,3750.0,male,2007